# trigger rerun of workflow
name: Deploy-SQL
on:
    push:
        branches: [ main ]
        paths: [ templates/**, .github/workflows/deploy-sql-arm.yml ]

env:
    AZURE_RG: github-actions
    AZURE_SUBSCRIPTION: dc4c18ef-bbab-42bf-b38b-041da2f8ed00

jobs:
    create-sql-databases:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Create RG if needed
              uses: azure/cli@v1
              with:
                inlineScript: az group create --name ${{ env.AZURE_RG }} --location westeurope
            - name: Deploy SQL Server ARM template
              id: deploy-sql-server
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
                resourceGroupName: ${{ env.AZURE_RG }}
                template: ./templates/sqltemplate.json
                parameters: sqladmin=${{ secrets.SQL_ADMIN }} sqlpwd=${{ secrets.SQL_PWD }}
            - name: Show server name
              run: echo ${{ steps.deploy-sql-server.outputs.sqlservername }}
            - name: Deploy Databases with ARM template
              id: deploy-sql-db
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
                resourceGroupName: ${{ env.AZURE_RG }}
                template: ./templates/sqldbtemplate.json
                parameters: sqlserver=${{ steps.deploy-sql-server.outputs.sqlservername }}
